### ISSUE TITLE
Yobit Exchange - Support

### ISSUE THREAD

**Issue by reappergrimd** [osteth/DemonCoin#1]
Good Day Devs 

Hope you are well. i spoke to one of the support staff at Yobit and they have now put the coin in maintenance mode due to no updates since last year Aug. 

i now this isnt the most valueable coin in the world but was wondering if an update was possible. or even if you can guide me with some way i can support the coin to get it back in an active state. i like the coin :) and willing to assist.

**Comment by osteth** [comment]
absolutely, let me see if I can check the yobit update requirements and see if I can meet them.

**Comment by reappergrimd** [comment]
Great , i have been running nodes for your coin since i can remember so it would be a shame to see it waste away and just after its first block halving :)
